# Generated by Django 5.1 on 2024-09-09 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="datos",
            name="unit_b",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="datos",
            name="bw",
            field=models.CharField(default="0", max_length=100),
        ),
    ]
