# Generated by Django 5.1 on 2024-09-09 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_alter_datos_rd_alter_datos_vrf"),
    ]

    operations = [
        migrations.AddField(
            model_name="datos",
            name="interface_swb",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="datos",
            name="swb",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
