# Generated by Django 5.1 on 2024-09-09 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_datos_unit_b_alter_datos_bw"),
    ]

    operations = [
        migrations.AddField(
            model_name="datos",
            name="bundle_ether_b",
            field=models.CharField(
                choices=[
                    ("N/A", "N/A"),
                    ("Bundle-ether10", "Bundle-ether10"),
                    ("Bundle-ether11", "Bundle-ether11"),
                    ("Bundle-ether12", "Bundle-ether12"),
                    ("Bundle-ether13", "Bundle-ether13"),
                    ("Bundle-ether14", "Bundle-ether14"),
                    ("Bundle-ether32", "Bundle-ether32"),
                    ("Bundle-ether33", "Bundle-ether33"),
                ],
                default="N/A",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="datos",
            name="interface_pe_b",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="datos",
            name="pe_b",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
