# Generated by Django 5.1 on 2024-09-10 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_datos_bundle_ether_b_datos_interface_pe_b_datos_pe_b"),
    ]

    operations = [
        migrations.RenameField(
            model_name="datos",
            old_name="interface_swb",
            new_name="interface_sw_b",
        ),
        migrations.RenameField(
            model_name="datos",
            old_name="swb",
            new_name="sw_b",
        ),
    ]
