# Generated by Django 5.1 on 2024-09-10 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0004_rename_interface_swb_datos_interface_sw_b_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="datos",
            name="sede_b",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
