# Generated by Django 5.1 on 2024-09-09 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0004_alter_datos_asn_alter_datos_bw_alter_datos_dko_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datos",
            name="wan",
            field=models.CharField(default="default_sede", max_length=100),
        ),
    ]
