# Generated by Django 5.1 on 2024-09-10 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0005_datos_sede_b"),
    ]

    operations = [
        migrations.AddField(
            model_name="datos",
            name="rfs_ip_port_b",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
