# Generated by Django 5.1 on 2024-09-09 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0005_alter_datos_wan"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datos",
            name="bundle_ether",
            field=models.CharField(
                choices=[
                    ("N/A", "N/A"),
                    ("Bundle-ether10", "Bundle-ether10"),
                    ("Bundle-ether11", "Bundle-ether11"),
                    ("Bundle-ether12", "Bundle-ether12"),
                    ("Bundle-ether13", "Bundle-ether13"),
                    ("Bundle-ether14", "Bundle-ether14"),
                    ("Bundle-ether32", "Bundle-ether32"),
                    ("Bundle-ether33", "Bundle-ether33"),
                ],
                default="N/A",
                max_length=100,
            ),
        ),
    ]
