# Generated by Django 5.1 on 2024-09-10 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0006_datos_rfs_ip_port_b"),
    ]

    operations = [
        migrations.AddField(
            model_name="datos",
            name="tipo_equipo",
            field=models.CharField(
                choices=[
                    ("", ""),
                    ("ALCATEL", "ALCATEL"),
                    ("jUNIPER", "jUNIPER"),
                    ("CISCO", "CISCO"),
                ],
                default="",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="datos",
            name="tipo_configuracion",
            field=models.CharField(
                choices=[
                    ("", ""),
                    ("Ampliacion", "Ampliacion"),
                    ("BGP", "BGP"),
                    ("Alta", "Alta"),
                    ("Modificacion", "Modificacion"),
                ],
                default="default_config",
                max_length=100,
            ),
        ),
    ]
