# Generated by Django 5.1 on 2024-09-10 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0007_datos_tipo_equipo_alter_datos_tipo_configuracion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datos",
            name="tipo_equipo",
            field=models.CharField(
                choices=[
                    ("", ""),
                    ("JUNIPER", "JUNIPER"),
                    ("ALCATEL", "ALCATEL"),
                    ("CISCO", "CISCO"),
                ],
                default="",
                max_length=100,
            ),
        ),
    ]
