# Generated by Django 5.1 on 2024-09-10 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0008_alter_datos_tipo_equipo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datos",
            name="tipo_equipo",
            field=models.CharField(
                choices=[("", ""), ("VPN", "VPN"), ("VPLS", "VPLS"), ("ADI", "ADI")],
                default="",
                max_length=100,
            ),
        ),
    ]
