# Generated by Django 5.1 on 2024-09-11 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0009_alter_datos_tipo_equipo"),
    ]

    operations = [
        migrations.AddField(
            model_name="datos",
            name="num_ptos",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="datos",
            name="tipo_equipo",
            field=models.CharField(
                choices=[
                    ("", ""),
                    ("JUNIPER", "JUNIPER"),
                    ("ALCATEL", "ALCATEL"),
                    ("CISCO", "CISCO"),
                ],
                default="",
                max_length=100,
            ),
        ),
    ]
