# Generated by Django 5.1 on 2024-09-16 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0011_rename_num_ptos_datos_puertos_lag"),
    ]

    operations = [
        migrations.AddField(
            model_name="datos",
            name="IES",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
