# Generated by Django 5.1 on 2024-09-25 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0014_datos_lanv6"),
    ]

    operations = [
        migrations.AddField(
            model_name="datos",
            name="administrative_state",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="datos",
            name="nodo",
            field=models.CharField(
                choices=[
                    (
                        "BGO2 / Telepuerto Suba- Colombia",
                        "BGO2 / Telepuerto Suba- Colombia",
                    ),
                    ("BGO1 / Colombia XV- Colombia", "BGO1 / Colombia XV- Colombia"),
                    ("CAL1 / Santa Monica- Colombia", "CAL1 / Santa Monica- Colombia"),
                    ("MDC4 / Santillana- Colombia", "MDC4 / Santillana- Colombia"),
                ],
                default="",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="datos",
            name="sfp",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="datos",
            name="lan",
            field=models.CharField(default="0.0.0.0/0", max_length=100),
        ),
        migrations.AlterField(
            model_name="datos",
            name="puertos_lag",
            field=models.CharField(default="1", max_length=100),
        ),
    ]
