# Generated by Django 5.1 on 2024-09-25 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0015_datos_administrative_state_datos_nodo_datos_sfp_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="datos",
            name="administrative_state",
        ),
        migrations.RemoveField(
            model_name="datos",
            name="nodo",
        ),
        migrations.RemoveField(
            model_name="datos",
            name="sfp",
        ),
        migrations.AddField(
            model_name="datos",
            name="mercado",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="datos",
            name="pais",
            field=models.CharField(
                choices=[
                    ("Argentina", "Argentina"),
                    ("Brazil", "Brazil"),
                    ("Chile", "Chile"),
                    ("Colombia", "Colombia"),
                    ("Ecuador", "Ecuador"),
                    ("Mexico", "Mexico"),
                    ("Peru", "Peru"),
                ],
                default="Colombia",
                max_length=100,
            ),
        ),
    ]
