# Generated by Django 5.1 on 2024-10-03 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0017_datos_be_alter_datos_bundle_ether_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="datos",
            name="rfs_ip_port_nid",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="datos",
            name="bundle_ether",
            field=models.CharField(
                choices=[
                    ("N/A", "N/A"),
                    ("Bundle-ether10", "Bundle-ether10"),
                    ("Bundle-ether11", "Bundle-ether11"),
                    ("Bundle-ether12", "Bundle-ether12"),
                    ("Bundle-ether13", "Bundle-ether13"),
                    ("Bundle-ether14", "Bundle-ether14"),
                    ("Bundle-ether32", "Bundle-ether32"),
                    ("Bundle-ether33", "Bundle-ether33"),
                    ("TE7/3", "TE7/3"),
                    ("GigabitEthernet0/11", "GigabitEthernet0/11"),
                ],
                default="N/A",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="datos",
            name="bundle_ether_b",
            field=models.CharField(
                choices=[
                    ("N/A", "N/A"),
                    ("Bundle-ether10", "Bundle-ether10"),
                    ("Bundle-ether11", "Bundle-ether11"),
                    ("Bundle-ether12", "Bundle-ether12"),
                    ("Bundle-ether13", "Bundle-ether13"),
                    ("Bundle-ether14", "Bundle-ether14"),
                    ("Bundle-ether32", "Bundle-ether32"),
                    ("Bundle-ether33", "Bundle-ether33"),
                    ("TE7/3", "TE7/3"),
                    ("GigabitEthernet0/11", "GigabitEthernet0/11"),
                ],
                default="N/A",
                max_length=100,
            ),
        ),
    ]
