# Generated by Django 5.1 on 2024-10-03 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0018_datos_rfs_ip_port_nid_alter_datos_bundle_ether_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="datos",
            name="unit_nid",
            field=models.CharField(default="505", max_length=100),
        ),
    ]
