# Generated by Django 5.1 on 2024-10-06 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0020_datos_bw_exchange_datos_bw_plus_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datos",
            name="cfs",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
