# Generated by Django 5.1 on 2024-10-10 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_alter_datos_lan_alter_datos_unit_nid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datos',
            name='lan',
            field=models.CharField(default='0.0.0.0/0', max_length=8000),
        ),
        migrations.AlterField(
            model_name='datos',
            name='lanv6',
            field=models.CharField(blank=True, max_length=8000, null=True),
        ),
    ]
