# Generated by Django 5.1 on 2024-10-16 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_alter_datos_lan_alter_datos_lanv6'),
    ]

    operations = [
        migrations.AddField(
            model_name='datos',
            name='cv_b',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='datos',
            name='sv_b',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
