# Generated by Django 5.1 on 2024-11-09 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_datos_cv_b_datos_sv_b'),
    ]

    operations = [
        migrations.AddField(
            model_name='datos',
            name='child_port',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='datos',
            name='encap_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='datos',
            name='mtu',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='datos',
            name='port_breakout',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='datos',
            name='root_port',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='datos',
            name='tipo_equipo',
            field=models.CharField(choices=[('', ''), ('JUNIPER', 'JUNIPER'), ('ALCATEL', 'ALCATEL'), ('ALCATEL_V', 'ALCATEL_V'), ('CISCO', 'CISCO')], default='', max_length=100),
        ),
    ]
