# Generated by Django 5.1 on 2024-11-09 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_datos_child_port_datos_encap_type_datos_mtu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datos',
            name='encap_type',
            field=models.CharField(choices=[('', ''), ('dot1q', 'dot1q'), ('qinq', 'qinq')], default='', max_length=100),
        ),
    ]
