# Generated by Django 5.1 on 2024-12-01 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_datos_lag_administrative_key_alter_datos_encap_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='datos',
            name='pe_vpls_a',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='datos',
            name='bundle_ether',
            field=models.CharField(choices=[('N/A', 'N/A'), ('Bundle-ether10', 'Bundle-ether10'), ('Bundle-ether11', 'Bundle-ether11'), ('Bundle-ether12', 'Bundle-ether12'), ('Bundle-ether13', 'Bundle-ether13'), ('Bundle-ether14', 'Bundle-ether14'), ('Bundle-ether32', 'Bundle-ether32'), ('Bundle-ether33', 'Bundle-ether33'), ('TE7/3', 'TE7/3'), ('GigabitEthernet0/11', 'GigabitEthernet0/11'), ('ae1', 'ae1'), ('SUBA', 'SUBA'), ('CXV', 'CXV')], default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='datos',
            name='bundle_ether_b',
            field=models.CharField(choices=[('N/A', 'N/A'), ('Bundle-ether10', 'Bundle-ether10'), ('Bundle-ether11', 'Bundle-ether11'), ('Bundle-ether12', 'Bundle-ether12'), ('Bundle-ether13', 'Bundle-ether13'), ('Bundle-ether14', 'Bundle-ether14'), ('Bundle-ether32', 'Bundle-ether32'), ('Bundle-ether33', 'Bundle-ether33'), ('TE7/3', 'TE7/3'), ('GigabitEthernet0/11', 'GigabitEthernet0/11'), ('ae1', 'ae1'), ('SUBA', 'SUBA'), ('CXV', 'CXV')], default='N/A', max_length=100),
        ),
    ]
