# Generated by Django 5.1 on 2024-12-01 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_datos_pe_vpls_a_alter_datos_bundle_ether_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datos',
            name='interface_pe_vpls_a',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='datos',
            name='interface_pe_vpls_b',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='datos',
            name='pe_vpls_b',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
