# Generated by Django 5.1 on 2024-12-02 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_datos_interface_pe_vpls_a_datos_interface_pe_vpls_b_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datos',
            name='lb_pe_vpls_a',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='datos',
            name='lb_pe_vpls_b',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
