# Generated by Django 5.1 on 2025-02-06 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_datos_lb_pe_vpls_a_datos_lb_pe_vpls_b'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datos',
            old_name='bw_Exchange',
            new_name='bw_exchange',
        ),
        migrations.RenameField(
            model_name='datos',
            old_name='IES',
            new_name='ies',
        ),
        migrations.AddField(
            model_name='datos',
            name='vrf_init',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='datos',
            name='bundle_ether',
            field=models.CharField(choices=[('N/A', 'N/A'), ('Bundle-ether10', 'Bundle-ether10'), ('Bundle-ether11', 'Bundle-ether11'), ('Bundle-ether12', 'Bundle-ether12'), ('Bundle-ether13', 'Bundle-ether13'), ('Bundle-ether14', 'Bundle-ether14'), ('Bundle-ether32', 'Bundle-ether32'), ('Bundle-ether33', 'Bundle-ether33'), ('TE7/3', 'TE7/3'), ('GigabitEthernet0/11', 'GigabitEthernet0/11'), ('ae1', 'ae1'), ('ae2', 'ae2'), ('SUBA', 'SUBA'), ('CXV', 'CXV')], default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='datos',
            name='bundle_ether_b',
            field=models.CharField(choices=[('N/A', 'N/A'), ('Bundle-ether10', 'Bundle-ether10'), ('Bundle-ether11', 'Bundle-ether11'), ('Bundle-ether12', 'Bundle-ether12'), ('Bundle-ether13', 'Bundle-ether13'), ('Bundle-ether14', 'Bundle-ether14'), ('Bundle-ether32', 'Bundle-ether32'), ('Bundle-ether33', 'Bundle-ether33'), ('TE7/3', 'TE7/3'), ('GigabitEthernet0/11', 'GigabitEthernet0/11'), ('ae1', 'ae1'), ('ae2', 'ae2'), ('SUBA', 'SUBA'), ('CXV', 'CXV')], default='N/A', max_length=100),
        ),
    ]
