# Generated by Django 5.1 on 2025-02-12 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0031_rename_bw_exchange_datos_bw_exchange_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datos',
            name='vrf2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
