# Generated by Django 5.1 on 2025-02-12 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0032_datos_vrf2'),
    ]

    operations = [
        migrations.AddField(
            model_name='datos',
            name='rd2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
