# Generated by Django 5.1 on 2025-02-13 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0033_datos_rd2'),
    ]

    operations = [
        migrations.AddField(
            model_name='datos',
            name='bw_video',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='datos',
            name='bw_voz',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
