# Generated by Django 5.1 on 2025-02-16 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0034_datos_bw_video_datos_bw_voz'),
    ]

    operations = [
        migrations.AddField(
            model_name='datos',
            name='lb_pe',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
